### PR TITLE
Vine parser

### PR DESCRIPTION
**Pull request by heavyk**
hi, I added the vine player

then, we needed different sizes so I abstracted out the options and updated the README

### CODE REVIEW

**Comment by brianjgeiger** [comment]
Sorry this has taken so long for me to look at. Apparently I missed the notification in October. It looks good; once I get a chance to functionally test it, I'll be able to merge it in.

**Comment by heavyk** [comment]
cool. it's been working this whole time for us. the only thing is, vine isn't easy like youtube to get the id. so, some people find it impossible to find the id for vine videos. I don't really know how to solve that easily, but the code does work as promised :)

cheers

**Comment by brianjgeiger** [comment]
Awesome, thanks!

**Comment by brianjgeiger** [comment]
Closing in favor of #10

**Pull request closed without merging**
