### PR TITLE
Add vine parser

### PR DESCRIPTION
**Pull request by heavyk**
this fixes a bug in the parser which looks for '(' starting at the beginning of the string (so if there's any '(' before the video tag, the parser will go into an infinite loop.this PR builds on the vine parser PR

### CODE REVIEW

**Comment by heavyk** [comment]
just pushed another commit which updates the url parsers. previously a vine url such as `https://vine.co/v/MhQ2lvg29Un/embed` would not match.

**Comment by heavyk** [comment]
just pushed another commit which fixes 2 space indentation and makes the service provider flexible. eg. now in the options, one can override the `url` field with another function which can parse more urls. for example, in our case we needed to integrate a service called 'vertele' so our options now look like this:

``` js
.use(require('markdown-it-video'), {
  url: function video_url(service, videoID, options) {
    switch (service) {
      case 'youtube': return '//www.youtube.com/embed/' + videoID;
      case 'vimeo': return '//player.vimeo.com/video/' + videoID;
      case 'vine': return '//vine.co/v/' + videoID + '/embed/' + options.vine.embed;
      case 'vertele':
        var id = videoID.split('|')
        return `http://cdnapi.kaltura.com/p/1910301/sp/191030100/embedIframeJs/uiconf_id/28928951/partner_id/1910301?iframeembed=true&playerId=verteletv-main-clip-${id[0]}&entry_id=${id[1]}&flashvars[streamerType]=auto`;
    }
  },
  youtube: {
    width: 250,
    height: 140,
  },
  vimeo: {
    width: 250,
    height: 140,
  },
  vine: {
    width: 250,
    height: 250,
    embed: 'simple?audio=1',
  },
  vertele: {
    width: 250,
    height: 140,
  },
})
```

cheers

**Comment by heavyk** [comment]
I should probably add documentation, but at the moment I do not have time. bug me and I'll do it.

**Comment by brianjgeiger** [comment]
Could you add some tests for vine to match the tests we have for youtube and vimeo? Otherwise this looks good.

**Comment by heavyk** [comment]
sure. will get to it tomorrow. cheers

**Comment by brianjgeiger** [comment]
Awesome, thanks! And if you were to pull in changes from Master, your build will be checked by Travis. I'm hoping the editor defaults you added will fix many of the linting problems as well.

**Comment by heavyk** [comment]
all done. everything is good now.

**Comment by heavyk** [comment]
oops, lemme see about rebasing to master.. one moment

**Comment by heavyk** [comment]
rebased - although there were no conflicts, travis seems to be failing still on linter errors.. investigating

**Comment by brianjgeiger** [comment]
Considering all the linter problems from before, those are things I can clean up. I just wanted to make sure I had your changes in before I started.

**Comment by heavyk** [comment]
got it. there were a shitload of errors. I'm off to bed. good nite!!

**Comment by heavyk** [comment]
force pushed a change that was pissing me off (make test tries to run the global eslint instead of the local node_modules one which is quite an old version)

**Comment by brianjgeiger** [comment]
Thank you very much for all your work on this.

**Comment by heavyk** [comment]
you're very welcome :) have a good night

**Pull request merged**
